project_id = "kamga"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/en", "http://localhost:3000/fr"]

[storage]
enabled = true
file_size_limit = "10MiB"